
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchArtist", targetNamespace = "http://service/", className = "service.SearchArtist")
    @ResponseWrapper(localName = "searchArtistResponse", targetNamespace = "http://service/", className = "service.SearchArtistResponse")
    @Action(input = "http://service/Service/searchArtistRequest", output = "http://service/Service/searchArtistResponse")
    public List<String> searchArtist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchGender", targetNamespace = "http://service/", className = "service.SearchGender")
    @ResponseWrapper(localName = "searchGenderResponse", targetNamespace = "http://service/", className = "service.SearchGenderResponse")
    @Action(input = "http://service/Service/searchGenderRequest", output = "http://service/Service/searchGenderResponse")
    public List<String> searchGender(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchName", targetNamespace = "http://service/", className = "service.SearchName")
    @ResponseWrapper(localName = "searchNameResponse", targetNamespace = "http://service/", className = "service.SearchNameResponse")
    @Action(input = "http://service/Service/searchNameRequest", output = "http://service/Service/searchNameResponse")
    public List<String> searchName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
